SELECT OUTS.ANIMAL_ID, OUTS.NAME
from ANIMAL_OUTS OUTS left join ANIMAL_INS INS
on OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.DATETIME < INS.DATETIME
ORDER BY INS.DATETIME;

-- https://programmers.co.kr/learn/courses/30/lessons/59043
