SELECT OUTS.ANIMAL_ID, OUTS.NAME
from ANIMAL_OUTS OUTS LEFT JOIN ANIMAL_INS INS
USING (ANIMAL_ID)
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2;

-- https://programmers.co.kr/learn/courses/30/lessons/59411
